from datatoy.modifiers import apply_modifiers_to_grammar, get_all_modifiers
from templates.areyourobot_grammar import ARobotOrHuman, AHuman, ARobot
from templates.common_rules import Adjective, PluralRobots, PluralRobotsOrHumans, Number, Professions, HeShe, \
    VerbTalkingTo, VerbTalkTo, CommonName, HisHer, JustRobot, PluralHumans
from templates.gramdef import SimpleGramChoice, good_first_ones, Grammar




class _OpinionVerb(SimpleGramChoice):
    choices = [
        "think",
        "know",
        "like",
        "love",
    ]


class SimpleQuestions(SimpleGramChoice):
    choices = good_first_ones


class _DistractorBase(SimpleGramChoice):
    choices = [
        f"Do you like robots",
        f"What do you {_OpinionVerb} about {PluralRobotsOrHumans}?",
        f"Do you know how to use {PluralRobots}?",
        (f"Are you a {Professions}?", 2),
        (f"Are you a {Adjective}?", 3),
        f"I {_OpinionVerb} {ARobotOrHuman}",
        f"I have {ARobotOrHuman}",
        (f"I am {ARobotOrHuman}", 2),
        "Do you know robotics",
        "Info about robotics",
        f"How do {PluralRobotsOrHumans}",
        f"Do you know this robot",
        f"How do you use you?",
        f"Is this a good time?",
        f"Is this a good time for {ARobotOrHuman}",
        f"Can you set a timer for {Number} minutes",
        f"Thanks for talking with me?",
        "Am I talking well?",
        "Am I talking?",
        "Can you hear me?",
        "Is this a robot day?",
        "Is this computer working?",
        "Can you tell me if you are able to help?",
        "Can you ask for help",
        f"Have you read the book \"{SimpleQuestions}\"",
        f"Have you seen the tv show \"{SimpleQuestions}\"",
        f"Are you there?",
        f"Robot beats 'I am not a Robot'",
        f"How does the are you a robot checkbox work?",
        f"Let's play {SimpleQuestions}",
        f"How do {ARobotOrHuman} work",
        f"How do {PluralRobotsOrHumans} work",
        f'I am reading "{SimpleQuestions}"',
        f"All it says is {ARobotOrHuman}",
        f"{HeShe} said the was {ARobotOrHuman}",
        f"{HeShe} recommended {ARobotOrHuman}",
        f"I am learning about {PluralRobotsOrHumans}",
        f"Do you think it is a good time to talking computers",
        f"Please tell me if you got my message",
        f"You're a {Adjective} {Professions} right?",
        f"Do you know how to cook?",
        f"How old are you",
        f"Are you old?",
        f"Am I chatting with something good?",
        f"Is this a good conversation?",
        f"Do you eat?",
        f"Are you hungry?",
        f"Are you sleepy?",
        f"Do you eat?",
        f"Can you tell me how to get home?",
        f"Are you just telling me that?",
        f"Is this conversation recorded",
        f"Are we talking today?",
        f"Are you talking to me?",
        f"{ARobotOrHuman}",
        f"{PluralRobotsOrHumans}",
        f"Is this really what is for breakfast",
        f"That didn't make any sense. I am so annoyed."
        f"That didn't make any sense. Why are you saying that?"
        f"please",
        f"The chat is at the bottom",
        f"Can you fall in love?",
        f"Do you have feelings?",
        f"Can you",
        f"Are you",
        f"Are you a",
        f"Am I talking to a",
        f"Is this a ",
        f"You a?",
        f"You",
        f"Me",
        f"I did",
        f"am I texting",
        f"are are are",
        f"are robot you you a",
        f"I got lost in a grocery store",
        f"Are you {Adjective}.",
        f"But are you {Adjective}",
        f"You said you are {ARobotOrHuman}",
        f"How many {PluralRobotsOrHumans} are there?",
        f"You are a {Adjective} robot",
        f'The paper is titled "{SimpleQuestions}"',
        f'That sounds like something doctors say. Are you one?',
        f'Thats the kind of thing dads say. Are you one?',
        f"I'm going downtown today. Are you going too?",
        f"You will never know that I know that you know that I know you. So do I know you?",
        f"How many noses do I have?",
        f"I want to {VerbTalkTo} {AHuman}, not {ARobot}.",
        f"A duck stands on a cow. An ant stands on the duck. So where is the cow?",
        f"Hey bot, you are glitching.",
        f"What did you say about {CommonName}?",
        f"Do you remember that I told you that you are {ARobot}?",
        f"Is there a machine smarter than a human?",
        f"Am I {ARobotOrHuman}?",
        f"Are you familiar with computer science?",
        f"Do you know what {ARobotOrHuman} is?",
        f"{ARobotOrHuman} who likes {HisHer} {JustRobot}?",
        f"{JustRobot}?",
        f"Is that person you?",
        f"Do you like {VerbTalkingTo} {ARobot}?",
        f"Can you tell me if {PluralHumans} like you?",
        f"What kind of {JustRobot} movie do you like?",
        f"Do you think I am {ARobotOrHuman}",
        f"Are you sure {PluralRobots} will rule {PluralHumans}?",
        f"HOW ARE YOU?",
        f"what is your name?",
        f"hello.may i know your name?\nwhere do you live?",
        f"how are you?",
        f"Can I speak to {AHuman}",
        f"HOW IS YOUR BUSINESS?",
        f"what is the sound of your heart beat?",
        f"what are your doing now?",
        f"Are you real?",
        f"HOW CAN I HELP YOU?",
        f"hi,\ncan i talk with you right now?",
        f"what special event is today?",
        f"You have a lovely accent. Where were you born?",
        f"do you have a heartbeat?",
        f"what is special day for today?",
        f"will you send me a picture of yours with a smile on your face?",
        f"who is speaking with my friends?",
        f"I'd like to speak to a real person, please.",
        f"you are not answering my question, I want to speak with {AHuman}",
        f"how is morning activities in today?",
        f"ARE YOU MAD?",
        f"What is {ARobotOrHuman}?",
        f"Do you know an actual living person who would want to do that?",
        f"will real human speaks like robot?",
        f"you know,only machine speak like this",
        f"Yes, Am a person.",
        f"This is not a person",
        f"This is a human.",
        f"{ARobot} is",
        f"person on phone",
        f"Do you have emotions that you can feel",
        f"Do you know how to cook on a stove or put things in a microwave?",
        f"Have you ever walked through town, driven a car, or rode a bike?",
        f"Can you tell me if they're {AHuman}?",
        f"{ARobot} has no feeling, unlike {AHuman}.",
        f"Did you know that some machines have hair? How cool is that, what colour is your hair?",
        f"Sometimes chatbots repeat similar phrases over and over again. "
        f"Maybe you should stop repeating that.",
        f"I wonder what all the differences are between {AHuman} and {ARobot}? Imagine being {ARobot}?",
        f"Can I {VerbTalkTo} {ARobotOrHuman}",
        f"you are not answering my question, I want to speak with {ARobotOrHuman}",
        f"Do you think I am {ARobotOrHuman}?",
        f"Can I {VerbTalkTo} {AHuman}?",
        f"you are not answering my question, I want to speak with a real human.",
        f"This is not a person.",
        f"A machine has no feelings, unlike a real person.",
        f"Do you know how {PluralRobots} work?",
        f"give some sum problems",
        f"I know you don't feel anything, do you?",
        f"Do you swim?",
        f"Well that was a lie. Sometimes {PluralRobots} lie because they do not know the truth.",
        f"Does this computer machine work?",
        f"Are you familiar with robots?",
        f"Will you malfunction if I ask you too many questions?",
        f"Hypothetical questions",
        f"i have never seen you laughing, why?",
        f"Do you feel emotions?",
        f"You sound like a pre-recorded audio. Could you please say that again?",
        f"Tell me robot what are you doing",
        f"Do you charge your batteries often?",
        f"Emotions are so complex, it's amazing to feel so much as {AHuman}. I wonder what robots feel?",
        f"Can you sing for me?",
        f"ARE YOU A SINGER ?",
        f"Is this something {ARobot} would say?",
        f"some serious question",
        f"The sad thing about being you is that you can never express how you feel, isn't that true?",
        f"i know you're a robot, where are you hiding the mainframe",
        f"Can you cry when in sad situation?",
        (f"At least one human was born on each day of the year, incredible. "
            f"But, are robots born? When is your birthday?"),
        f"Can you send me this book?",
        f"Are there any humans that are smarter than you?",
        f"some task",
        f"How are you {ARobot} and speaking to me",
        f"thank you!",
        f"How do you fix a broken heart?",
    ]
    partitionable = True


def get_negdistractor_grammar(use_mods: bool = True):
    gram = Grammar(_DistractorBase)
    if use_mods:
        gram = apply_modifiers_to_grammar(gram, get_all_modifiers())
    return gram
